name: test
on: [push]
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: test
      run: |
        go test ./cmd/